/**
 * Copyright (C) 2018 Laboratory of Experimental Biophysics
 * Ecole Polytechnique Federale de Lausanne
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ch.epfl.leb.alica.acpack.analyzers.defcon;

import ch.epfl.leb.alica.interfaces.analyzers.AnalyzerStatusPanel;

/**
 * Status panel of the DEFCoN analyzer.
 * 
 * @author Kyle M. Douglass
 */
public class DefconStatusPanel extends AnalyzerStatusPanel {
    
    /**
     * A reference to the core DEFCoN machinery.
     */
    private Defcon defcon;
    
    /**
     * Creates new form DefconStatusPanel.
     */
    public DefconStatusPanel(Defcon defcon) {
        this.defcon = defcon;
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCountType = new javax.swing.ButtonGroup();
        labelDefcon = new javax.swing.JLabel();
        cbLiveView = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        rbTotalCount = new javax.swing.JRadioButton();
        rbLocalCount = new javax.swing.JRadioButton();
        lBoxSize = new javax.swing.JLabel();
        tfBoxSize = new javax.swing.JTextField();

        labelDefcon.setText("DEFCoN");

        cbLiveView.setText("Live view");
        cbLiveView.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLiveViewItemStateChanged(evt);
            }
        });

        bgCountType.add(rbTotalCount);
        rbTotalCount.setSelected(true);
        rbTotalCount.setText("Total count");
        rbTotalCount.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbTotalCountItemStateChanged(evt);
            }
        });

        bgCountType.add(rbLocalCount);
        rbLocalCount.setText("Maximum local count");
        rbLocalCount.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbLocalCountItemStateChanged(evt);
            }
        });

        lBoxSize.setText("Box size");
        lBoxSize.setEnabled(false);

        tfBoxSize.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfBoxSize.setText("7");
        tfBoxSize.setEnabled(false);
        tfBoxSize.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfBoxSizeFocusLost(evt);
            }
        });
        tfBoxSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBoxSizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lBoxSize)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfBoxSize))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbLocalCount)
                                .addComponent(rbTotalCount)
                                .addComponent(labelDefcon)
                                .addComponent(cbLiveView)))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDefcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbLiveView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbTotalCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbLocalCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBoxSize)
                    .addComponent(tfBoxSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbLiveViewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLiveViewItemStateChanged
        if (cbLiveView.isSelected()) {
            defcon.liveModeOn();
        } else {
            defcon.liveModeOff();
        }
    }//GEN-LAST:event_cbLiveViewItemStateChanged

    private void rbTotalCountItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbTotalCountItemStateChanged
        if ( rbTotalCount.isSelected() ) {
            defcon.maxLocalCountOff();
            lBoxSize.setEnabled(false);
            tfBoxSize.setEnabled(false);
        }
    }//GEN-LAST:event_rbTotalCountItemStateChanged

    private void rbLocalCountItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbLocalCountItemStateChanged
        if ( rbLocalCount.isSelected() ) {
            lBoxSize.setEnabled(true);
            tfBoxSize.setEnabled(true);
            defcon.maxLocalCountOn();
            defcon.setBoxSize(Integer.valueOf(tfBoxSize.getText()));
        }
    }//GEN-LAST:event_rbLocalCountItemStateChanged

    private void tfBoxSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBoxSizeActionPerformed
        defcon.setBoxSize(Integer.valueOf(tfBoxSize.getText()));
    }//GEN-LAST:event_tfBoxSizeActionPerformed

    private void tfBoxSizeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBoxSizeFocusLost
        defcon.setBoxSize(Integer.valueOf(tfBoxSize.getText()));
    }//GEN-LAST:event_tfBoxSizeFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCountType;
    private javax.swing.JCheckBox cbLiveView;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lBoxSize;
    private javax.swing.JLabel labelDefcon;
    private javax.swing.JRadioButton rbLocalCount;
    private javax.swing.JRadioButton rbTotalCount;
    private javax.swing.JTextField tfBoxSize;
    // End of variables declaration//GEN-END:variables
}
